[package]
name = "experiment"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]

[dependencies]
cgmath = "0.7.0"
glium = "0.13.5"
itertools = "0.4.10"
vtime = { path = "../time" }
