[package]
name = "geodesic"
version = "0.1.0"
authors = [
    "Brendan Zabarauskas <bjzaba@yahoo.com.au>",
    "Chip Collier <photex@gmail.com>",
]

[dependencies]
cgmath = "0.7"
glium = "0.13"
itertools = "0.4"
time = "0.1"
