[package]
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>", "Chip Collier <photex@gmail.com>"]
name = "voyager"
version = "0.0.1"

[[bin]]
name = "voyager"
path = "voyager/src/main.rs"

[[bin]]
name = "geodesic"
path = "geodesic/src/main.rs"

[dependencies]
cgmath = "0.9.1"
find_folder = "0.3.0"
glium = "0.14.0"
imgui = "0.0.8"
num-traits = "0.1"
quick-error = "1.0.0"
rand = "^0.3.14"
rayon = "0.4.0"
rusttype = "0.2.0"
time = "0.1.34"

[lib]
name = "vtime"
path = "time/src/lib.rs"
