[package]
authors = [
    "Brendan Zabarauskas <bjzaba@yahoo.com.au>",
    "Chip Collier <photex@gmail.com>",
]
name = "voyager"
version = "0.0.1"

[[bin]]
name = "voyager"
path = "voyager/src/main.rs"

[[bin]]
name = "geodesic"
path = "geodesic/src/main.rs"

[dependencies]
cgmath = "0.7.0"
glium = "0.13.5"
glutin = "0.4.9"
rand = "^0.3.14"
rusttype = "0.1.2"
time = "0.1.34"

[lib]
name = "vtime"
path = "time/src/lib.rs"
