[package]
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>", "Chip Collier <photex@gmail.com>"]
name = "voyager"
version = "0.0.1"

[dependencies]
cgmath = "0.10.0"
clippy = {version = "0.0.75", optional = true}
find_folder = "0.3.0"
glium = "0.14.0"
imgui = "0.0.8"
maplit = "0.1.3"
notify = "2.5.5"
num-traits = "0.1"
quick-error = "1.0.0"
rand = "^0.3.14"
rayon = "0.4.0"
rusttype = "0.2.0"
time = "0.1.34"
itertools = "0.4.15"

[dev-dependencies]
expectest = "0.5.1"

[features]
default=[]
