[package]
name = "voyager"
version = "0.2.0"
authors = []

[dependencies]
amethyst = "0.9"
derivative = "1.0"
log = "0.4"
gfx = { version = "0.17", features = ["serialize"] }
glsl-layout = { version = "0.1.1", features = ["cgmath", "gfx"] }
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"