[package]
name = "voyager"
version = "0.3.0"
authors = ["Brendan", "Chip"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
env_logger = "0.7"
rand = "0.7"
wgpu = { git="git://github.com/gfx-rs/wgpu-rs.git" }
nalgebra = "0.18"
ncollide3d = "0.20"
winit = "0.20.0-alpha3"
pyro = "0.2"
