[workspace]
members = [
    "./crates/pikelet",
    "./crates/pikelet-driver",
    "./crates/pikelet-elaborate",
    "./crates/pikelet-language-server",
    "./crates/pikelet-repl",
    "./crates/pikelet-syntax",
]
